"""report_draft.md (bilingual CN/EN) → report_draft.tex (English only) sync and check tool.

Sync rule: only the **[Pn-EN]** paragraphs of the md go into the tex; [Pn-CN] and everything else stays out.
Consistency guarantee: the tex file is a generated artifact (never edit by hand); every run makes it
match the English part of the md exactly; if the md numbering is discontinuous, CN/EN are unpaired or
the tex disagrees with the md, the script raises an error and shows the differences.

Usage:
  python -X utf8 scripts/sync_report_draft.py           # validate structure and regenerate the tex
  python -X utf8 scripts/sync_report_draft.py --check   # check only (no writes); non-zero exit on mismatch
"""
import re
import sys
from datetime import datetime
from pathlib import Path

MD_PATH = Path("docs/submission/report_draft.md")
TEX_PATH = Path("docs/submission/report_draft.tex")

SEC_RE = re.compile(r"^##\s+(\d+)\.\s+(.+?)\s*/\s*(.+?)\s*$")
PAR_RE = re.compile(r"^\*\*\[P(\d+)-(CN|EN)\]\*\*\s*(.*)$")

# common Unicode → LaTeX mapping (escape first, then map; the $ { } introduced by the mapping are safe code)
UNICODE_MAP = {
    "κ": r"$\kappa$", "Δ": r"$\Delta$", "δ": r"$\delta$", "λ": r"$\lambda$",
    "≤": r"$\leq$", "≥": r"$\geq$", "≈": r"$\approx$", "×": r"$\times$",
    "±": r"$\pm$", "−": r"$-$", "→": r"$\rightarrow$", "≠": r"$\neq$",
    "–": "--", "—": "---", "…": r"\dots{}",
    "‘": "`", "’": "'", "“": "``", "”": "''",
}
ESC_CHARS = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
             "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
             "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def latex_escape(text: str) -> str:
    """Single character-level escape pass (avoids double escaping), then the Unicode mapping."""
    out = []
    for ch in text:
        if ch in ESC_CHARS:
            out.append(ESC_CHARS[ch])
        else:
            out.append(ch)
    text = "".join(out)
    for src, dst in UNICODE_MAP.items():
        text = text.replace(src, dst)
    return text


def parse_md(text: str):
    """Parse md → (sections, problems); sections is an ordered list."""
    sections = []
    problems = []
    cur = None
    pending = None  # (num, lang, lines)

    def flush_para():
        nonlocal pending
        if pending is None:
            return
        num, lang, lines = pending
        body = " ".join(seg.strip() for seg in lines if seg.strip())
        if not body:
            problems.append(f"[P{num}-{lang}] paragraph body is empty")
        cur["paras"].append({"num": num, "lang": lang, "text": body})
        pending = None

    for line in text.splitlines():
        m_sec = SEC_RE.match(line)
        m_par = PAR_RE.match(line)
        if m_sec:
            flush_para()
            cur = {"number": m_sec.group(1), "en": m_sec.group(2).strip(),
                   "cn": m_sec.group(3).strip(), "paras": []}
            sections.append(cur)
        elif m_par:
            flush_para()
            if cur is None:
                problems.append(f"[P{m_par.group(1)}-{m_par.group(2)}] appears before any section heading")
                cur = {"number": "?", "en": "(no section)", "cn": "", "paras": []}
                sections.append(cur)
            pending = (int(m_par.group(1)), m_par.group(2), [m_par.group(3)])
        elif pending is not None:
            pending[2].append(line)
    flush_para()

    # structural validation: numbers continuous and unique, CN/EN paired
    nums = {}
    for sec in sections:
        for p in sec["paras"]:
            nums.setdefault(p["num"], []).append(p["lang"])
    for num in sorted(nums):
        langs = nums[num]
        if langs.count("CN") != 1 or langs.count("EN") != 1:
            problems.append(f"[P{num}] CN/EN not paired: {langs}")
    if nums:
        expect = list(range(1, max(nums) + 1))
        if sorted(nums) != expect:
            missing = sorted(set(expect) - set(nums))
            problems.append(f"numbering is not continuous; missing: {missing}")
    for sec in sections:
        if not sec["paras"]:
            problems.append(f"section {sec['number']}. {sec['en']} has no paragraphs")
    return sections, problems


def build_tex(sections, generated_line: str) -> str:
    """Build the complete tex from the English sections/paragraphs. An empty generated_line omits the timestamp (for --check comparison)."""
    head = [
        "%% ============================================================================",
        "%% AUTOMATICALLY GENERATED — DO NOT EDIT MANUALLY / this file is auto-generated by script; do not edit by hand",
        "%% Source  : docs/submission/report_draft.md  ([Pn-EN] English paragraphs only)",
        "%% Rebuild : python -X utf8 scripts/sync_report_draft.py",
    ]
    if generated_line:
        head.append(f"%% {generated_line}")
    head += [
        "%% Match   : the %% [Pn] comment before each paragraph is its number in report_draft.md",
        "%% ============================================================================",
        r"\documentclass[11pt,a4paper]{article}",
        r"\usepackage[a4paper,margin=2.4cm]{geometry}",
        r"\usepackage[T1]{fontenc}",
        r"\usepackage[utf8]{inputenc}",
        r"\usepackage{microtype}",
        r"\usepackage[hidelinks]{hyperref}",
        r"\setlength{\parskip}{0.5em}",
        r"\setlength{\parindent}{0pt}",
        r"\title{Final Report Writing Guide --- English Typeset Copy}",
        r"\author{auto-generated from \texttt{report\_draft.md}}",
        r"\date{September 2026}",
        r"\begin{document}",
        r"\maketitle",
        "",
    ]
    body = []
    for sec in sections:
        body.append("% " + "-" * 74)
        body.append(rf"\section*{{{sec['number']}. {latex_escape(sec['en'])}}}")
        for p in sec["paras"]:
            if p["lang"] == "EN":
                body.append(f"% [P{p['num']}]")
                body.append(latex_escape(p["text"]))
                body.append("")
    tail = [r"\end{document}", ""]
    return "\n".join(head + body + tail)


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    text = MD_PATH.read_text(encoding="utf-8")
    sections, problems = parse_md(text)

    para_total = sum(len(s["paras"]) for s in sections)
    en_total = sum(1 for s in sections for p in s["paras"] if p["lang"] == "EN")
    print(f"[sync_report_draft] parsed: {len(sections)} sections / {para_total} paragraphs / {en_total} English")

    # warning for unmapped non-ASCII characters (advisory only; does not affect generation)
    unmapped = set()
    for sec in sections:
        for p in sec["paras"]:
            if p["lang"] != "EN":
                continue
            for ch in p["text"]:
                if ord(ch) > 0x24F and ch not in UNICODE_MAP:
                    unmapped.add(ch)
    if unmapped:
        print(f"[sync_report_draft] warning: unmapped non-ASCII characters kept in the tex: {sorted(unmapped)}")

    if problems:
        print("[sync_report_draft] structural errors:")
        for item in problems:
            print("  -", item)
        return 2

    generated = datetime.now().strftime("Generated: %Y-%m-%d %H:%M")
    expected_tex = build_tex(sections, generated_line="")  # for comparison (no timestamp)
    write_tex = build_tex(sections, generated_line=generated)

    if check_only:
        if not TEX_PATH.exists():
            print(f"[sync_report_draft] tex does not exist: {TEX_PATH}")
            return 1
        actual = TEX_PATH.read_text(encoding="utf-8").replace("\r\n", "\n")
        actual = "\n".join(
            ln for ln in actual.split("\n") if not ln.startswith("%% Generated:")
        )
        if actual.rstrip() != expected_tex.rstrip():
            print("[sync_report_draft] mismatch: the tex differs from the English part of the md (the tex may have been edited by hand or not synced)")
            a = actual.rstrip().split("\n")
            e = expected_tex.rstrip().split("\n")
            for i in range(max(len(a), len(e))):
                la = a[i] if i < len(a) else "<none>"
                le = e[i] if i < len(e) else "<none>"
                if la != le:
                    print(f"  first difference (line {i+1}):\n    tex : {la}\n    md  : {le}")
                    break
            return 1
        print("[sync_report_draft] in sync: the tex matches the English part of the md exactly")
        return 0

    TEX_PATH.write_text(write_tex, encoding="utf-8", newline="\n")
    print(f"[sync_report_draft] generated {TEX_PATH} ({len(write_tex.splitlines())} lines, {generated})")
    print("[sync_report_draft] tip: run --check at any time to verify consistency")
    return 0


if __name__ == "__main__":
    sys.exit(main())
